# Set up the turkish response for the given english input
to_turkish = {
    "The entered user does not have the required permissions" : "Girilen kullanıcının gerekli izinleri yok",
    "This name is reserved, please enter another name" : "Bu isim rezervedir, lütfen başka bir isim girin",
    "You haven't completed enough credits for scholarship" : "Burs için yeterli kredi tamamlamadınız",
    "You haven't taken enough courses to apply for scholarship" : "Burs için yeterli ders almadınız",
    "User is not verified, no access provided" : "Kullanıcı doğrulanmadı, erişim sağlanmadı",
    "Enter your credentials to authorize" : "Yetkilendirmek için kimlik bilgilerinizi girin",
    "You have a very low GPA for scholarship" : "Burs için çok düşük bir GPA'nız var",
    "You have a perfect GPA for scholarship" : "Burs için mükemmel bir GPA'nız var",
    "New Credit must be between 0 and 7" : "Yeni Kredi 0 ile 7 arasında olmalıdır",
    "User is verified, access provided" : "Kullanıcı doğrulandı, erişim sağlandı",
    "A document with this name already exists" : "Bu isimde bir belge zaten var",
    "You are not eligible for a scholarship" : "Bir burs için uygun değilsiniz",
    "Please select a course to remove" : "Lütfen kaldırmak için bir ders seçin",
    "Please enter a name for the document" : "Lütfen belge için bir isim girin",
    "You have a high GPA for scholarship" : "Burs için yüksek bir GPA'nız var",
    "You have a nice GPA for scholarship" : "Burs için güzel bir GPA'nız var",
    "You are eligible for a %25 scholarship" : "Bir %25 burs için uygunsunuz",
    "You are eligible for a %40 scholarship" : "Bir %40 burs için uygunsunuz",
    "You are eligible for a %50 scholarship" : "Bir %50 burs için uygunsunuz",
    "You have a low GPA for scholarship" : "Burs için düşük bir GPA'nız var",
    "You have a good GPA for scholarship" : "Burs için iyi bir GPA'nız var",
    "No Course Must Taken Again" : "Tekrar Alınmak Zorunda Olan Ders Yok",
    "Please select at least one filter" : "Lütfen en az bir filtre seçin",
    "No Course Should Taken Again" : "Tekrar Alınması Gereken Ders Yok",
    "Courses Must Taken Again" : "Tekrar Alınması Zorunlu Olan Dersler",
    "New Grade Point must be numeric" : "Yeni Not Puanı sayı olmalıdır",
    "No data found for this user" : "Bu kullanıcı için veri bulunamadı",
    "Unauthorized Access Verification" : "Yetkisiz Erişim Doğrulaması",
    "New Credit must be an integer" : "Yeni Kredi bir sayı olmalıdır",
    "Please select a filter value" : "Lütfen bir filtre değeri seçin",
    "Courses Should Taken Again" : "Tekrar Alınması Gereken Dersler",
    "Please fill all the fields" : "Lütfen tüm alanları doldurun",
    "Enter a name for the document" : "Belge için bir isim girin",
    "Select a document to load" : "Yüklemek için bir belge seçin",
    "Please select a course code" : "Lütfen bir ders kodu seçin",
    "Select and Remove filters" : "Filtreleri Seçin / kaldırın",
    "Login to Authorize :" : "Yetkilendirmek için Giriş Yap :",
    "Select and Update Course" : "Ders Seçin ve Güncelleyin",
    "Semester Based Performance" : "Dönem Bazlı Performans",
    "Select and Remove Course" : "Ders Seçin ve Kaldırın",
    "Please select a document" : "Lütfen bir belge seçin",
    "Course Based Performance" : "Ders Bazlı Performans",
    "Course Code already exists" : "Ders Kodu zaten var",
    "This filter already exists" : "Bu filtre zaten var",
    "Credits Included in GPA" : "GPA'ya Dahil Krediler",
    "Existing Course Grade Point" : "Mevcut Ders Puanı",
    "Existing Course Credit" : "Mevcut Ders Kredisi",
    "Write and Add Course" : "Ders Yazın ve Ekleyin",
    "Select Output Folder" : "Çıktı Klasörünü Seçin",
    "Existing Course Language" : "Mevcut Ders Dili",
    "Exporting Data" : "Veriler Dışa Aktarılıyor",
    "Existing Course Grade" : "Mevcut Ders Notu",
    "New Course Grade Point" : "Yeni Ders Puanı",
    "Existing Course Code" : "Mevcut Ders Kodu",
    "Sort by Grade Point" : "Puana Göre Sırala",
    "Credits Successful" : "Başarılı Krediler",
    "Existing Course Name" : "Mevcut Ders Adı",
    "Language of Instruction" : "Öğretim Dili",
    "Faculty / Department" : "Fakülte / Bölüm",
    "New Course Credit" : "Yeni Ders Kredisi",
    "Grade Point Average" : "Not Ortalaması",
    "Credits Attempted" : "Denenen Krediler",
    "New Course Language" : "Yeni Ders Dili",
    "Sort by Credit" : "Krediye Göre Sırala",
    "Sort by Language" : "Dile Göre Sırala",
    "Filter Courses" : "Dersleri Filtrele",
    "Saving Data" : "Veriler Kaydediliyor",
    "New Course Grade" : "Yeni Ders Notu",
    "Export Data" : "Verileri Dışa Aktar",
    "Loading Data" : "Veriler Yükleniyor",
    "National ID" : "T.C Kimlik Numarası",
    "Scholarship Status" : "Burs Durumu",
    "New Course Code" : "Yeni Ders Kodu",
    "Sort by Grade" : "Nota Göre Sırala",
    "Course Grade Point" : "Ders Puanı",
    "New Course Name" : "Yeni Ders Adı",
    "Filter By" : "Tarafından Filtrele",
    "Sort by Name" : "İsme Göre Sırala",
    "Sort by Code" : "Koda Göre Sırala",
    "Student Status" : "Öğrenci Durumu",
    "Update Course" : "Ders Güncelle",
    "Student ID" : "Öğrenci Numarası",
    "Course Credit" : "Ders Kredisi",
    "Invalid grade" : "Geçersiz not",
    "Course Language" : "Ders Dili",
    "Remove Course" : "Ders Kaldır",
    "Save Data" : "Verileri Kaydet",
    "Filter With" : "İle Filtrele",
    "Load Data" : "Verileri Yükle",
    "Program Name" : "Program Adı",
    "Grade Notation" : "Notasyon",
    "Filtering" : "Filtreleniyor",
    "Username" : "Kullanıcı Adı",
    "Course Grade" : "Ders Notu",
    "Updating" : "Güncelleniyor",
    "Resetting" : "Sıfırlanıyor",
    "Restart" : "Yeniden Başlat",
    "Refreshing" : "Yenileniyor",
    "Course Code" : "Ders Kodu",
    "Removing" : "Kaldırılıyor",
    "Processing" : "İşleniyor",
    "Course Name" : "Ders Adı",
    "Add Course" : "Ders Ekle",
    "Success" : "Başarılı",
    "Percentage" : "Yüzde",
    "Grade Point" : "Puan",
    "Adding" : "Ekleniyor",
    "Footnote" : "Dipnot",
    "Operation" : "İşlem",
    "Surname" : "Soyisim",
    "Password" : "Şifre",
    "Refresh" : "Yenile",
    "Message" : "Mesaj",
    "Remove" : "Kaldır",
    "Reset" : "Sıfırla",
    "Spring" : "Bahar",
    "Credit" : "Kredi",
    "Language" : "Dil",
    "Apply" : "Uygula",
    "Cancel" : "İptal",
    "Login" : "Giriş",
    "Save" : "Kaydet",
    "Summer" : "Yaz",
    "Error" : "Hata",
    "Exit" : "Çıkış",
    "Load" : "Yükle",
    "Grade" : "Not",
    "Name" : "İsim",
    "Fall" : "Güz",
    "Add" : "Ekle",
    "GPA" : "GPA",
}