
to_turkish = {
    "Student ID" : "Öğrenci Numarası",
    "National ID" : "T.C Kimlik Numarası",
    "Name" : "İsim",
    "Surname" : "Soyisim",
    "Faculty / Department" : "Fakülte / Bölüm",
    "Program Name" : "Program Adı",
    "Language of Instruction" : "Öğretim Dili",
    "Student Status" : "Öğrenci Durumu",

    "Load" : "Yükle",
    "Save" : "Kaydet",
    "Load Data" : "Verileri Yükle",
    "Save Data" : "Verileri Kaydet",
    "Saving Data" : "Veriler Kaydediliyor",
    "Loading Data" : "Veriler Yükleniyor",
    "Exit" : "Çıkış",
    "Reset" : "Sıfırla",
    "Restart" : "Yeniden Başlat",
    "Export Data" : "Verileri Dışa Aktar",
    "Select a document to load" : "Yüklemek için bir belge seçin",
    "Cancel" : "İptal",
    "Enter a name for the document" : "Belge için bir isim girin",
    "Error" : "Hata",
    "Please enter a name for the document" : "Lütfen belge için bir isim girin",
    "A document with this name already exists" : "Bu isimde bir belge zaten var",
    "No data found for this user" : "Bu kullanıcı için veri bulunamadı",
    "Select Output Folder" : "Çıktı Klasörünü Seçin",
    "Exporting Data" : "Veriler Dışa Aktarılıyor",
    "Resetting" : "Sıfırlanıyor",
    "Please select a document" : "Lütfen bir belge seçin",
    "This name is reserved, please enter another name" : "Bu isim rezervedir, lütfen başka bir isim girin",

    "Filter Courses" : "Dersleri Filtrele",
    "Update Course" : "Ders Güncelle",
    "Add Course" : "Ders Ekle",
    "Remove Course" : "Ders Kaldır",
    "Sort by Code" : "Koda Göre Sırala",
    "Sort by Name" : "İsme Göre Sırala",
    "Sort by Language" : "Dile Göre Sırala",
    "Sort by Credit" : "Krediye Göre Sırala",
    "Sort by Grade" : "Nota Göre Sırala",
    "Sort by Grade Point" : "Puana Göre Sırala",
}